import { AVATAR_IDS } from './profile-store.js';

export const MATCH_FOUND_DELAY_MS = 1500;

const rosterDetails = [
  ['MayaTiles', 'US'], ['Theo_92', 'GB'], ['SakuraTea', 'JP'], ['LucaMoves', 'IT'],
  ['MinaMoon', 'KR'], ['EmreCan', 'TR'], ['SofiaSol', 'ES'], ['NoahNorth', 'CA'],
  ['NoraPlays', 'DE'], ['Hana_7', 'JP'], ['KaiRiver', 'NZ'], ['AmelieRose', 'FR'],
  ['ArjunChai', 'IN'], ['LinhLan', 'VN'], ['LeoLima', 'BR'], ['EllaGreen', 'AU'],
  ['YukiMatcha', 'JP'], ['FelixFox', 'DE'], ['InesAzul', 'PT'], ['DaraDay', 'IE'],
  ['Aylin88', 'TR'], ['JaeMin', 'KR'], ['ClaraBloom', 'FR'], ['OwenOak', 'GB'],
  ['MeiLin_24', 'TW'], ['MateoRio', 'MX'], ['FreyaFrost', 'NO'], ['RaviSun', 'IN'],
  ['ZoePebble', 'AU'], ['AriaFinch', 'US'], ['NicoEspresso', 'IT'], ['SanneSea', 'NL'],
  ['Tessa_19', 'CA'], ['KenjiKoi', 'JP'], ['EceDeniz', 'TR'], ['LucasVale', 'BR'],
  ['IrisMint', 'BE'], ['MinSeo', 'KR'], ['DiegoLuz', 'ES'], ['ElsaBirch', 'SE'],
  ['AmirAtlas', 'MA'], ['LilyLoops', 'GB'], ['BaoBamboo', 'VN'], ['EvaMoss', 'DE'],
  ['Benji_31', 'US'], ['AnikaRain', 'IN'], ['LouisBleu', 'FR'], ['MilaMaple', 'CA'],
  ['RenSora', 'JP'], ['OliviaBee', 'AU'], ['Jules_84', 'BE'], ['CemArda', 'TR'],
  ['DaisyDot', 'GB'], ['HugoCosta', 'PT'], ['JinPark', 'KR'], ['LaraLeaf', 'CH'],
  ['RosaLuna', 'MX'], ['OscarPine', 'SE'], ['NinaPeach', 'US'], ['TuanTran', 'VN'],
  ['AlessiaM', 'IT'], ['Kiran_8', 'IN'], ['FinnHarbor', 'IE'], ['CamilleBee', 'FR'],
  ['AlinaSnow', 'PL'], ['TomTulip', 'NL'], ['Haruto_16', 'JP'], ['BiaMar', 'BR'],
  ['SelinSu', 'TR'], ['ChloeFern', 'NZ'], ['AdrianSol', 'ES'], ['SooJin_9', 'KR'],
  ['LenaLark', 'DE'], ['MarcoOlive', 'IT'], ['AliceWren', 'GB'], ['DevPatel', 'IN'],
  ['Lucia_27', 'AR'], ['EthanCedar', 'CA'], ['NadiaJade', 'MY'], ['RemyPear', 'FR'],
  ['YunaCloud', 'JP'], ['SamirTea', 'EG'], ['Poppy_11', 'AU'], ['DaviCoco', 'BR'],
  ['IvyChen', 'SG'], ['HenrikLake', 'DK'], ['DeryaMavi', 'TR'], ['ElenaAlba', 'ES'],
  ['RileyMorn', 'US'], ['QuynhLotus', 'VN'], ['PetraPine', 'CZ'], ['Minho_23', 'KR'],
  ['AoifeRain', 'IE'], ['ChenWei', 'TW'], ['MartaSun', 'PT'], ['OliverReed', 'NZ'],
  ['EmmaBrooks', 'US'], ['PabloLopez', 'ES'], ['AdelaDvorak', 'CZ'], ['EmilianoSoto', 'MX'],
  ['MargotDubois', 'FR'], ['MaltheHolm', 'DK'], ['TrangDang', 'VN'], ['HarveyHart', 'AU'],
  ['AstridLind', 'SE'], ['YitingChen', 'TW'], ['AlfieShaw', 'GB'], ['DuarteSousa', 'PT'],
  ['ElifAydin', 'TR'], ['FrancoVera', 'AR'], ['LuisaBraun', 'DE'], ['ToivoSalmi', 'FI'],
  ['AnaSilva', 'BR'], ['CianWalsh', 'IE'], ['MajaBerg', 'NO'], ['MarcusWong', 'SG'],
  ['SophieWalker', 'CA'], ['ThijsMulder', 'NL'], ['HinaAbe', 'JP'], ['DanishAziz', 'MY'],
  ['CarmenGarcia', 'ES'], ['JakubSvoboda', 'CZ'], ['XimenaRuiz', 'MX'], ['GabrielBernard', 'FR'],
  ['AgnesAndersen', 'DK'], ['DuyVo', 'VN'], ['ZaraKing', 'AU'], ['ArneGoossens', 'BE'],
  ['JiahaoLin', 'TW'], ['IslaHill', 'GB'], ['LeonorCosta', 'PT'], ['MertCelik', 'TR'],
  ['AgustinaPaz', 'AR'], ['AntonSchulz', 'DE'], ['IidaLehto', 'FI'], ['NikhilVerma', 'IN'],
  ['OrlaByrne', 'IE'], ['SanderOlsen', 'NO'], ['VanessaLee', 'SG'], ['HudsonCampbell', 'CA'],
  ['AnoukMeijer', 'NL'], ['ItsukiKubo', 'JP'], ['NadiaHamid', 'MY'], ['RiccardoMarino', 'IT'],
  ['TerezaNovak', 'CZ'], ['SantiagoPerez', 'MX'], ['JuliettePetit', 'FR'], ['MikkelLarsen', 'DK'],
  ['HuongHoang', 'VN'], ['AngusBrown', 'AU'], ['LienClaes', 'BE'], ['TaeyangLim', 'KR'],
  ['HarryClarke', 'GB'], ['TiagoSantos', 'PT'], ['ZeynepDemir', 'TR'], ['JoaquinRojas', 'AR'],
  ['GretaHoffmann', 'DE'], ['LauriSaari', 'FI'], ['KavyaIyer', 'IN'], ['QuinnClark', 'NZ'],
  ['IngridHansen', 'NO'], ['DarrenLim', 'SG'], ['AveryWilson', 'CA'], ['BramBos', 'NL'],
  ['RinAoki', 'JP'], ['IrfanOmar', 'MY'], ['BiancaLeone', 'IT'], ['KacperPawlak', 'PL'],
  ['ValeriaCruz', 'MX'], ['EnzoMoreau', 'FR'], ['IdaHansen', 'DK'], ['PhucPham', 'VN'],
  ['BillieMurray', 'AU'], ['MathisWillems', 'BE'], ['NariHan', 'KR'], ['OwenWells', 'US'],
  ['BeatrizSilva', 'PT'], ['KeremKaya', 'TR'], ['MartinaDiaz', 'AR'], ['EmilBecker', 'DE'],
  ['KerttuMakela', 'FI'], ['VihaanKapoor', 'IN'], ['HazelYoung', 'NZ'], ['AlbinNyberg', 'SE'],
  ['RachelTan', 'SG'], ['LoganFraser', 'CA'], ['FemkeSmit', 'NL'], ['SotaKato', 'JP'],
  ['AlyaIsmail', 'MY'], ['LorenzoBruno', 'IT'], ['JuliaDudek', 'PL'], ['BrunoDias', 'BR'],
  ['ManonLaurent', 'FR'], ['MagnusJensen', 'DK'], ['ThaoLe', 'VN'], ['ArchieWhite', 'AU'],
  ['HanneMertens', 'BE'], ['JisungKang', 'KR'], ['GraceMorgan', 'US'], ['AndresCano', 'ES'],
  ['DefneYilmaz', 'TR'], ['BautistaGomez', 'AR'], ['FriedaWagner', 'DE'], ['OnniAalto', 'FI'],
  ['NehaNair', 'IN'], ['TobySmith', 'NZ'], ['KlaraSjoberg', 'SE'], ['ZhiyuChang', 'TW'],
  ['CharlotteMartin', 'CA'], ['DaanVisser', 'NL'], ['AoiMori', 'JP'], ['FarisAhmad', 'MY'],
  ['ChiaraCosta', 'IT'], ['OskarKaczmarek', 'PL'], ['YasminMelo', 'BR'], ['FionnKelly', 'IE'],
  ['AlmaNielsen', 'DK'], ['KhoaTran', 'VN'], ['RubyKelly', 'AU'], ['WoutJacobs', 'BE'],
  ['HaeunJung', 'KR'], ['EthanParker', 'US'], ['LolaMarin', 'ES'], ['MatejHorak', 'CZ'],
  ['DelfinaLopez', 'AR'], ['JonasFischer', 'DE'], ['VenlaKoski', 'FI'], ['AaravShah', 'IN'],
  ['TuiLewis', 'NZ'], ['ArvidEk', 'SE'], ['PeilinYang', 'TW'], ['ArthurGreen', 'GB'],
  ['LotteBakker', 'NL'], ['KaitoTanaka', 'JP'], ['NurulHassan', 'MY'], ['DavideConti', 'IT'],
  ['HannaWozniak', 'PL'], ['ThiagoRocha', 'BR'], ['MaeveQuinn', 'IE'], ['EskilStrand', 'NO'],
  ['NgocNguyen', 'VN'], ['LachlanRyan', 'AU'], ['FienMaes', 'BE'], ['DohyunChoi', 'KR'],
  ['MiaBennett', 'US'], ['SergioRamos', 'ES'], ['EliskaVesely', 'CZ'], ['GaelRios', 'MX'],
  ['JohannaWeber', 'DE'], ['EeroNiemi', 'FI'], ['PriyaRao', 'IN'], ['FlynnMoore', 'NZ'],
  ['SagaHolm', 'SE'], ['XinyiTsai', 'TW'], ['ElsieCooper', 'GB'], ['TomasRocha', 'PT'],
  ['AkariSato', 'JP'], ['HakimRahman', 'MY'], ['AuroraGallo', 'IT'], ['FilipKrawczyk', 'PL'],
  ['HelenaAlves', 'BR'], ['EoinFlynn', 'IE'], ['TheaDahl', 'NO'], ['AdrianTeo', 'SG'],
  ['MatildaWalsh', 'AU'], ['SeppeJanssens', 'BE'], ['SeoyeonPark', 'KR'], ['LiamReed', 'US'],
  ['VegaVidal', 'ES'], ['TomasKucera', 'CZ'], ['RenataLuna', 'MX'], ['BastienSimon', 'FR'],
  ['AinoLaine', 'FI'], ['RohanMehta', 'IN'], ['ArohaJones', 'NZ'], ['NilsDahl', 'SE'],
  ['YuxuanLiu', 'TW'], ['GeorgeBell', 'GB'], ['CarolinaGomes', 'PT'], ['OnurYildiz', 'TR'],
  ['AinaYusof', 'MY'], ['MatteoRicci', 'IT'], ['AlicjaMazur', 'PL'], ['RafaelSouza', 'BR'],
  ['SaoirseRyan', 'IE'], ['EvenMoen', 'NO'], ['CherylChua', 'SG'], ['NolanEllis', 'CA'],
  ['FleurPeeters', 'BE'], ['HyunwooLee', 'KR'], ['AvaHayes', 'US'], ['JavierRubio', 'ES'],
  ['KarolinaP31', 'CZ'], ['AlejandroVega', 'MX'], ['EliseLeroy', 'FR'], ['AsgerMadsen', 'DK'],
  ['AditiSharma', 'IN'], ['KoaBaker', 'NZ'], ['EbbaLund', 'SE'], ['JunjieWu', 'TW'],
  ['PippaWood', 'GB'], ['JoaoLopes', 'PT'], ['AsliSahin', 'TR'], ['TomasSosa', 'AR'],
  ['GiuliaRossi', 'IT'], ['JanKowalski', 'PL'], ['LuizaLima', 'BR'], ['RonanDoyle', 'IE'],
  ['OdaLarsen', 'NO'], ['BryanKoh', 'SG'], ['NoraTaylor', 'CA'], ['StijnVos', 'NL'],
  ['JiwooKim', 'KR'], ['NoahCarter', 'US'], ['AlbaDiaz', 'ES'], ['LukasCerny', 'CZ'],
  ['CamilaLeon', 'MX'], ['AntoineRoux', 'FR'], ['SigneLund', 'DK'], ['NamBui', 'VN'],
  ['MaiaScott', 'NZ'], ['AxelBerg', 'SE'], ['ZihanHuang', 'TW'], ['ImogenTurner', 'GB'],
  ['MarianaPereira', 'PT'], ['BurakArslan', 'TR'], ['EmiliaMolina', 'AR'], ['MoritzWolf', 'DE'],
  ['ZofiaNowak', 'PL'], ['PedroCosta', 'BR'], ['NiamhMurphy', 'IE'], ['AkselSolberg', 'NO'],
  ['AliciaGoh', 'SG'], ['CalebRoss', 'CA'], ['MaartjeJansen', 'NL'], ['DaikiOno', 'JP'],
  ['cian_49', 'IE'], ['maja_22', 'NO'], ['marcus_83', 'SG'], ['sophie_64', 'CA'],
  ['thijs_37', 'NL'], ['hina_98', 'JP'], ['danish_71', 'MY'], ['carmen_52', 'ES'],
  ['jakub_25', 'CZ'], ['ximena_86', 'MX'], ['gabriel_67', 'FR'], ['agnes_40', 'DK'],
  ['duy_13', 'VN'], ['zara_82', 'AU'], ['arne_55', 'BE'], ['jiahao_28', 'TW'],
  ['isla_97', 'GB'], ['leonor_70', 'PT'], ['mert_43', 'TR'], ['agustina_16', 'AR'],
  ['anton_85', 'DE'], ['iida_58', 'FI'], ['nikhil_31', 'IN'], ['orla_12', 'IE'],
  ['sander_73', 'NO'], ['vanessa_46', 'SG'], ['hudson_27', 'CA'], ['anouk_88', 'NL'],
  ['itsuki_61', 'JP'], ['nadia_34', 'MY'], ['riccardo_15', 'IT'], ['tereza_76', 'CZ'],
  ['santiago_49', 'MX'], ['juliette_30', 'FR'], ['mikkel_91', 'DK'], ['huong_64', 'VN'],
  ['angus_45', 'AU'], ['lien_18', 'BE'], ['taeyang_79', 'KR'], ['harry_60', 'GB'],
  ['tiago_33', 'PT'], ['zeynep_94', 'TR'], ['joaquin_67', 'AR'], ['greta_48', 'DE'],
  ['lauri_21', 'FI'], ['kavya_82', 'IN'], ['quinn_63', 'NZ'], ['ingrid_36', 'NO'],
  ['darren_97', 'SG'], ['avery_78', 'CA'], ['bram_51', 'NL'], ['rin_24', 'JP'],
  ['irfan_85', 'MY'], ['bianca_66', 'IT'], ['kacper_39', 'PL'], ['valeria_12', 'MX'],
  ['enzo_81', 'FR'], ['ida_54', 'DK'], ['phuc_27', 'VN'], ['billie_96', 'AU'],
  ['mathis_69', 'BE'], ['nari_42', 'KR'], ['owen_23', 'US'], ['beatriz_84', 'PT'],
  ['kerem_57', 'TR'], ['martina_30', 'AR'], ['emil_11', 'DE'], ['kerttu_72', 'FI'],
  ['vihaan_45', 'IN'], ['hazel_26', 'NZ'], ['albin_87', 'SE'], ['rachel_60', 'SG'],
  ['logan_41', 'CA'], ['femke_14', 'NL'], ['sota_75', 'JP'], ['alya_48', 'MY'],
  ['lorenzo_29', 'IT'], ['julia_90', 'PL'], ['bruno_63', 'BR'], ['manon_44', 'FR'],
  ['magnus_17', 'DK'], ['thao_78', 'VN'], ['archie_59', 'AU'], ['hanne_32', 'BE'],
  ['jisung_93', 'KR'], ['grace_74', 'US'], ['andres_47', 'ES'], ['defne_20', 'TR'],
  ['bautista_81', 'AR'], ['frieda_62', 'DE'], ['onni_35', 'FI'], ['neha_96', 'IN'],
  ['toby_77', 'NZ'], ['klara_50', 'SE'], ['zhiyu_23', 'TW'], ['charlotte_92', 'CA'],
  ['daan_65', 'NL'], ['aoi_38', 'JP'], ['faris_11', 'MY'], ['chiara_80', 'IT'],
  ['oskar_53', 'PL'], ['yasmin_26', 'BR'], ['fionn_95', 'IE'], ['alma_68', 'DK'],
  ['khoa_41', 'VN'], ['ruby_22', 'AU'], ['wout_83', 'BE'], ['haeun_56', 'KR'],
  ['ethan_37', 'US'], ['lola_98', 'ES'], ['matej_71', 'CZ'], ['delfina_44', 'AR'],
  ['jonas_25', 'DE'], ['venla_86', 'FI'], ['aarav_59', 'IN'], ['tui_40', 'NZ'],
  ['arvid_13', 'SE'], ['peilin_74', 'TW'], ['arthur_55', 'GB'], ['lotte_28', 'NL'],
  ['kaito_89', 'JP'], ['nurul_62', 'MY'], ['davide_43', 'IT'], ['hanna_16', 'PL'],
  ['thiago_77', 'BR'], ['maeve_58', 'IE'], ['eskil_31', 'NO'], ['ngoc_92', 'VN'],
  ['lachlan_73', 'AU'], ['fien_46', 'BE'], ['dohyun_19', 'KR'], ['mia_88', 'US'],
  ['sergio_61', 'ES'], ['eliska_34', 'CZ'], ['gael_95', 'MX'], ['johanna_76', 'DE'],
  ['eero_49', 'FI'], ['priya_22', 'IN'], ['flynn_91', 'NZ'], ['saga_64', 'SE'],
  ['xinyi_37', 'TW'], ['elsie_18', 'GB'], ['tomas_79', 'PT'], ['akari_52', 'JP'],
  ['hakim_25', 'MY'], ['aurora_94', 'IT'], ['filip_67', 'PL'], ['helena_40', 'BR'],
  ['eoin_21', 'IE'], ['thea_82', 'NO'], ['adrian_55', 'SG'], ['matilda_36', 'AU'],
  ['seppe_97', 'BE'], ['seoyeon_70', 'KR'], ['liam_51', 'US'], ['vega_24', 'ES'],
  ['tomas_85', 'CZ'], ['renata_58', 'MX'], ['bastien_39', 'FR'], ['aino_12', 'FI'],
  ['rohan_73', 'IN'], ['aroha_54', 'NZ'], ['nils_27', 'SE'], ['yuxuan_88', 'TW'],
  ['george_69', 'GB'], ['carolina_42', 'PT'], ['onur_15', 'TR'], ['aina_76', 'MY'],
  ['matteo_57', 'IT'], ['alicja_30', 'PL'], ['rafael_91', 'BR'], ['saoirse_72', 'IE'],
  ['even_45', 'NO'], ['cheryl_18', 'SG'], ['nolan_87', 'CA'], ['fleur_60', 'BE'],
  ['hyunwoo_33', 'KR'], ['ava_14', 'US'], ['javier_75', 'ES'], ['karolina_48', 'CZ'],
  ['alejandro_21', 'MX'], ['elise_90', 'FR'], ['asger_63', 'DK'], ['aditi_36', 'IN'],
  ['koa_17', 'NZ'], ['ebba_78', 'SE'], ['junjie_51', 'TW'], ['pippa_32', 'GB'],
  ['joao_93', 'PT'], ['asli_66', 'TR'], ['tomas_39', 'AR'], ['giulia_20', 'IT'],
  ['jan_81', 'PL'], ['luiza_54', 'BR'], ['ronan_35', 'IE'], ['oda_96', 'NO'],
  ['bryan_69', 'SG'], ['nora_50', 'CA'], ['stijn_23', 'NL'], ['jiwoo_84', 'KR'],
  ['noah_65', 'US'], ['alba_38', 'ES'], ['lukas_11', 'CZ'], ['camila_72', 'MX'],
  ['antoine_53', 'FR'], ['signe_26', 'DK'], ['nam_87', 'VN'], ['maia_68', 'NZ'],
  ['axel_41', 'SE'], ['zihan_14', 'TW'], ['imogen_83', 'GB'], ['mariana_56', 'PT'],
  ['burak_29', 'TR'], ['emilia_90', 'AR'], ['moritz_71', 'DE'], ['zofia_44', 'PL'],
  ['pedro_17', 'BR'], ['niamh_86', 'IE'], ['aksel_59', 'NO'], ['alicia_32', 'SG'],
  ['caleb_13', 'CA'], ['maartje_74', 'NL'], ['daiki_47', 'JP'], ['emma_28', 'US'],
  ['pablo_89', 'ES'], ['adela_62', 'CZ'], ['emiliano_35', 'MX'], ['margot_16', 'FR'],
  ['malthe_77', 'DK'], ['trang_50', 'VN'], ['harvey_31', 'AU'], ['astrid_92', 'SE'],
  ['yiting_65', 'TW'], ['alfie_46', 'GB'], ['duarte_19', 'PT'], ['elif_80', 'TR'],
  ['franco_53', 'AR'], ['luisa_34', 'DE'], ['toivo_95', 'FI'], ['ana_68', 'BR'],
  ['LeonorTide', 'PT'], ['MertCocoa', 'TR'], ['AgustinaFern', 'AR'], ['AntonPebble', 'DE'],
  ['IidaChai', 'FI'], ['NikhilJade', 'IN'], ['OrlaMoss', 'IE'], ['SanderSky', 'NO'],
  ['VanessaWren', 'SG'], ['HudsonPeach', 'CA'], ['AnoukLotus', 'NL'], ['ItsukiOlive', 'JP'],
  ['NadiaBreeze', 'MY'], ['RiccardoLake', 'IT'], ['TerezaAcorn', 'CZ'], ['SantiagoOrchid', 'MX'],
  ['JulietteTide', 'FR'], ['MikkelCocoa', 'DK'], ['HuongFern', 'VN'], ['AngusPebble', 'AU'],
  ['LienChai', 'BE'], ['TaeyangJade', 'KR'], ['HarryMoss', 'GB'], ['TiagoSky', 'PT'],
  ['ZeynepWren', 'TR'], ['JoaquinKoi', 'AR'], ['GretaLotus', 'DE'], ['LauriOlive', 'FI'],
  ['KavyaBreeze', 'IN'], ['QuinnLake', 'NZ'], ['IngridAcorn', 'NO'], ['DarrenOrchid', 'SG'],
  ['AveryTide', 'CA'], ['BramCocoa', 'NL'], ['RinFern', 'JP'], ['IrfanSunny', 'MY'],
  ['BiancaChai', 'IT'], ['KacperJade', 'PL'], ['ValeriaFinch', 'MX'], ['EnzoSky', 'FR'],
  ['IdaWren', 'DK'], ['PhucKoi', 'VN'], ['BillieLotus', 'AU'], ['MathisOlive', 'BE'],
  ['NariBreeze', 'KR'], ['OwenLake', 'US'], ['BeatrizAcorn', 'PT'], ['KeremOrchid', 'TR'],
  ['MartinaDaisy', 'AR'], ['EmilCocoa', 'DE'], ['KerttuFern', 'FI'], ['VihaanSunny', 'IN'],
  ['HazelChai', 'NZ'], ['AlbinJade', 'SE'], ['RachelFinch', 'SG'], ['LoganSky', 'CA'],
  ['FemkeWren', 'NL'], ['SotaKoi', 'JP'], ['AlyaMaple', 'MY'], ['LorenzoOlive', 'IT'],
  ['JuliaBreeze', 'PL'], ['BrunoPine', 'BR'], ['ManonAcorn', 'FR'], ['MagnusOrchid', 'DK'],
  ['ThaoDaisy', 'VN'], ['ArchieCocoa', 'AU'], ['HanneFern', 'BE'], ['JisungSunny', 'KR'],
  ['GraceChai', 'US'], ['AndresJade', 'ES'], ['DefneFinch', 'TR'], ['BautistaBirch', 'AR'],
  ['FriedaWren', 'DE'], ['OnniKoi', 'FI'], ['NehaMaple', 'IN'], ['TobyOlive', 'NZ'],
  ['KlaraBreeze', 'SE'], ['ZhiyuPine', 'TW'], ['CharlotteAcorn', 'CA'], ['DaanOrchid', 'NL'],
  ['AoiDaisy', 'JP'], ['FarisClover', 'MY'], ['ChiaraFern', 'IT'], ['OskarSunny', 'PL'],
  ['YasminCedar', 'BR'], ['FionnJade', 'IE'], ['AlmaFinch', 'DK'], ['KhoaBirch', 'VN'],
  ['RubyWren', 'AU'], ['WoutKoi', 'BE'], ['HaeunMaple', 'KR'], ['EthanOlive', 'US'],
  ['LolaBreeze', 'ES'], ['MatejPine', 'CZ'], ['DelfinaCloud', 'AR'], ['JonasOrchid', 'DE'],
  ['VenlaDaisy', 'FI'], ['AaravClover', 'IN'], ['TuiFern', 'NZ'], ['ArvidSunny', 'SE'],
  ['PeilinCedar', 'TW'], ['ArthurJade', 'GB'], ['LotteFinch', 'NL'], ['KaitoBirch', 'JP'],
  ['NurulReef', 'MY'], ['DavideKoi', 'IT'], ['HannaMaple', 'PL'], ['ThiagoTea', 'BR'],
  ['MaeveBreeze', 'IE'], ['EskilPine', 'NO'], ['NgocCloud', 'VN'], ['LachlanOrchid', 'AU'],
  ['FienDaisy', 'BE'], ['DohyunClover', 'KR'], ['MiaFern', 'US'], ['SergioSunny', 'ES'],
  ['EliskaCedar', 'CZ'], ['GaelMoon', 'MX'], ['JohannaFinch', 'DE'], ['EeroBirch', 'FI'],
  ['PriyaReef', 'IN'], ['FlynnKoi', 'NZ'], ['SagaMaple', 'SE'], ['XinyiTea', 'TW'],
  ['ElsieBreeze', 'GB'], ['TomasPine', 'PT'], ['AkariCloud', 'JP'], ['HakimMint', 'MY'],
  ['AuroraDaisy', 'IT'], ['FilipClover', 'PL'], ['HelenaSage', 'BR'], ['EoinSunny', 'IE'],
  ['TheaCedar', 'NO'], ['AdrianMoon', 'SG'], ['MatildaFinch', 'AU'], ['SeppeBirch', 'BE'],
  ['SeoyeonReef', 'KR'], ['LiamKoi', 'US'], ['VegaMaple', 'ES'], ['TomasTea', 'CZ'],
  ['RenataWillow', 'MX'], ['BastienPine', 'FR'], ['AinoCloud', 'FI'], ['RohanMint', 'IN'],
  ['ArohaDaisy', 'NZ'], ['NilsClover', 'SE'], ['YuxuanSage', 'TW'], ['GeorgeSunny', 'GB'],
  ['CarolinaCedar', 'PT'], ['OnurMoon', 'TR'], ['AinaMoss', 'MY'], ['MatteoBirch', 'IT'],
  ['AlicjaReef', 'PL'], ['RafaelPeach', 'BR'], ['SaoirseMaple', 'IE'], ['EvenTea', 'NO'],
  ['CherylWillow', 'SG'], ['NolanPine', 'CA'], ['FleurCloud', 'BE'], ['HyunwooMint', 'KR'],
  ['AvaDaisy', 'US'], ['JavierClover', 'ES'], ['KarolinaSage', 'CZ'], ['AlejandroPebble', 'MX'],
  ['EliseCedar', 'FR'], ['AsgerMoon', 'DK'], ['AditiMoss', 'IN'], ['KoaBirch', 'NZ'],
  ['EbbaReef', 'SE'], ['JunjiePeach', 'TW'], ['PippaMaple', 'GB'], ['JoaoTea', 'PT'],
  ['AsliWillow', 'TR'], ['TomasLake', 'AR'], ['GiuliaCloud', 'IT'], ['JanMint', 'PL'],
  ['LuizaTide', 'BR'], ['RonanClover', 'IE'], ['OdaSage', 'NO'], ['BryanPebble', 'SG'],
  ['NoraCedar', 'CA'], ['StijnMoon', 'NL'], ['JiwooMoss', 'KR'], ['NoahBirch', 'US'],
  ['AlbaReef', 'ES'], ['LukasPeach', 'CZ'], ['CamilaLotus', 'MX'], ['AntoineTea', 'FR'],
  ['SigneWillow', 'DK'], ['NamLake', 'VN'], ['MaiaCloud', 'NZ'], ['AxelMint', 'SE'],
  ['ZihanTide', 'TW'], ['ImogenClover', 'GB'], ['MarianaSage', 'PT'], ['BurakPebble', 'TR'],
  ['EmiliaChai', 'AR'], ['MoritzMoon', 'DE'], ['ZofiaMoss', 'PL'], ['PedroSky', 'BR'],
  ['NiamhReef', 'IE'], ['AkselPeach', 'NO'], ['AliciaLotus', 'SG'], ['CalebTea', 'CA'],
  ['MaartjeWillow', 'NL'], ['DaikiLake', 'JP'], ['EmmaCloud', 'US'], ['PabloMint', 'ES'],
  ['AdelaTide', 'CZ'], ['EmilianoCocoa', 'MX'], ['MargotSage', 'FR'], ['MalthePebble', 'DK'],
  ['TrangChai', 'VN'], ['HarveyMoon', 'AU'], ['AstridMoss', 'SE'], ['YitingSky', 'TW'],
  ['AlfieReef', 'GB'], ['DuartePeach', 'PT'], ['ElifLotus', 'TR'], ['FrancoOlive', 'AR'],
  ['LuisaWillow', 'DE'], ['ToivoLake', 'FI'], ['AnaAcorn', 'BR'], ['CianMint', 'IE'],
  ['MajaTide', 'NO'], ['MarcusCocoa', 'SG'], ['SophieSage', 'CA'], ['ThijsPebble', 'NL'],
  ['HinaChai', 'JP'], ['DanishJade', 'MY'], ['CarmenMoss', 'ES'], ['JakubSky', 'CZ'],
  ['XimenaWren', 'MX'], ['GabrielPeach', 'FR'], ['AgnesLotus', 'DK'], ['DuyOlive', 'VN'],
  ['ZaraWillow', 'AU'], ['ArneLake', 'BE'], ['JiahaoAcorn', 'TW'], ['IslaMint', 'GB'],
  ['m.larsen', 'DK'], ['h.hoang', 'VN'], ['a.brown', 'AU'], ['l.claes', 'BE'],
  ['t.lim', 'KR'], ['h.clarke', 'GB'], ['t.santos', 'PT'], ['z.demir', 'TR'],
  ['j.rojas', 'AR'], ['g.hoffmann', 'DE'], ['l.saari', 'FI'], ['k.iyer', 'IN'],
  ['q.clark', 'NZ'], ['i.hansen', 'NO'], ['d.lim', 'SG'], ['a.wilson', 'CA'],
  ['b.bos', 'NL'], ['r.aoki', 'JP'], ['i.omar', 'MY'], ['b.leone', 'IT'],
  ['k.pawlak', 'PL'], ['v.cruz', 'MX'], ['e.moreau', 'FR'], ['i.hansen88', 'DK'],
  ['p.pham', 'VN'], ['b.murray', 'AU'], ['m.willems', 'BE'], ['n.han', 'KR'],
  ['o.wells', 'US'], ['b.silva', 'PT'], ['k.kaya', 'TR'], ['m.diaz', 'AR'],
  ['e.becker', 'DE'], ['k.makela', 'FI'], ['v.kapoor', 'IN'], ['h.young', 'NZ'],
  ['a.nyberg', 'SE'], ['r.tan', 'SG'], ['l.fraser', 'CA'], ['f.smit', 'NL'],
  ['s.kato', 'JP'], ['a.ismail', 'MY'], ['l.bruno', 'IT'], ['j.dudek', 'PL'],
  ['b.dias', 'BR'], ['m.laurent', 'FR'], ['m.jensen', 'DK'], ['t.le', 'VN'],
  ['a.white', 'AU'], ['h.mertens', 'BE'], ['j.kang', 'KR'], ['g.morgan', 'US'],
  ['a.cano', 'ES'], ['d.yilmaz', 'TR'], ['b.gomez', 'AR'], ['f.wagner', 'DE'],
  ['o.aalto', 'FI'], ['n.nair', 'IN'], ['t.smith', 'NZ'], ['k.sjoberg', 'SE'],
  ['z.chang', 'TW'], ['c.martin', 'CA'], ['d.visser', 'NL'], ['a.mori', 'JP'],
  ['f.ahmad', 'MY'], ['c.costa', 'IT'], ['o.kaczmarek', 'PL'], ['y.melo', 'BR'],
  ['f.kelly', 'IE'], ['a.nielsen', 'DK'], ['k.tran', 'VN'], ['r.kelly', 'AU'],
  ['w.jacobs', 'BE'], ['h.jung', 'KR'], ['e.parker', 'US'], ['l.marin', 'ES'],
  ['m.horak', 'CZ'], ['d.lopez', 'AR'], ['j.fischer', 'DE'], ['v.koski', 'FI'],
  ['a.shah', 'IN'], ['t.lewis', 'NZ'], ['a.ek', 'SE'], ['p.yang', 'TW'],
  ['a.green', 'GB'], ['l.bakker', 'NL'], ['k.tanaka', 'JP'], ['n.hassan', 'MY'],
  ['d.conti', 'IT'], ['h.wozniak', 'PL'], ['t.rocha', 'BR'], ['m.quinn', 'IE'],
  ['e.strand', 'NO'], ['n.nguyen', 'VN'], ['l.ryan', 'AU'], ['f.maes', 'BE'],
  ['d.choi', 'KR'], ['m.bennett', 'US'], ['s.ramos', 'ES'], ['e.vesely', 'CZ'],
  ['g.rios', 'MX'], ['j.weber', 'DE'], ['e.niemi', 'FI'], ['p.rao', 'IN'],
  ['f.moore', 'NZ'], ['s.holm', 'SE'], ['x.tsai', 'TW'], ['e.cooper', 'GB'],
  ['t.rocha25', 'PT'], ['a.sato', 'JP'], ['h.rahman', 'MY'], ['a.gallo', 'IT'],
  ['f.krawczyk', 'PL'], ['h.alves', 'BR'], ['e.flynn', 'IE'], ['t.dahl', 'NO'],
  ['a.teo', 'SG'], ['m.walsh', 'AU'], ['s.janssens', 'BE'], ['s.park', 'KR'],
  ['l.reed', 'US'], ['v.vidal', 'ES'], ['t.kucera', 'CZ'], ['r.luna', 'MX'],
  ['b.simon', 'FR'], ['a.laine', 'FI'], ['r.mehta', 'IN'], ['a.jones', 'NZ'],
  ['n.dahl', 'SE'], ['y.liu', 'TW'], ['g.bell', 'GB'], ['c.gomes', 'PT'],
  ['o.yildiz', 'TR'], ['a.yusof', 'MY'], ['m.ricci', 'IT'], ['a.mazur', 'PL'],
  ['r.souza', 'BR'], ['s.ryan', 'IE'], ['e.moen', 'NO'], ['c.chua', 'SG'],
  ['n.ellis', 'CA'], ['f.peeters', 'BE'], ['h.lee', 'KR'], ['a.hayes', 'US'],
  ['j.rubio', 'ES'], ['k.prochazka', 'CZ'], ['a.vega', 'MX'], ['e.leroy', 'FR'],
  ['a.madsen', 'DK'], ['a.sharma', 'IN'], ['k.baker', 'NZ'], ['e.lund', 'SE'],
  ['j.wu', 'TW'], ['p.wood', 'GB'], ['j.lopes', 'PT'], ['a.sahin', 'TR'],
  ['t.sosa', 'AR'], ['g.rossi', 'IT'], ['j.kowalski', 'PL'], ['l.lima', 'BR'],
  ['r.doyle', 'IE'], ['o.larsen', 'NO'], ['b.koh', 'SG'], ['n.taylor', 'CA'],
  ['s.vos', 'NL'], ['j.kim', 'KR'], ['n.carter', 'US'], ['a.diaz', 'ES'],
  ['l.cerny', 'CZ'], ['c.leon', 'MX'], ['a.roux', 'FR'], ['s.lund', 'DK'],
  ['n.bui', 'VN'], ['m.scott', 'NZ'], ['a.berg', 'SE'], ['z.huang', 'TW'],
  ['i.turner', 'GB'], ['m.pereira', 'PT'], ['b.arslan', 'TR'], ['e.molina', 'AR'],
  ['m.wolf', 'DE'], ['z.nowak', 'PL'], ['p.costa', 'BR'], ['n.murphy', 'IE'],
];

/** Local profiles for simulated opponents; these do not represent online players. */
export const OPPONENT_ROSTER = Object.freeze(rosterDetails.map(([name, countryCode], index) => Object.freeze({
  id: `opponent-${String(index + 1).padStart(3, '0')}`,
  version: 1,
  name,
  avatarId: AVATAR_IDS[index % AVATAR_IDS.length],
  countryCode,
  frameId: '',
})));

function randomFraction(random) {
  const value = random();
  return Number.isFinite(value) ? Math.max(0, Math.min(1 - Number.EPSILON, value)) : 0;
}

function comparableName(name) {
  return typeof name === 'string' ? name.normalize('NFKC').trim().toLowerCase() : '';
}

/** Keep successive opponents distinct, including their portrait beside the player. */
export function chooseOpponent({ player, previousId, random = Math.random } = {}) {
  const playerName = comparableName(player?.name);
  const candidates = OPPONENT_ROSTER.filter(opponent => (
    opponent.id !== previousId
    && comparableName(opponent.name) !== playerName
    && opponent.avatarId !== player?.avatarId
  ));
  return { ...candidates[Math.floor(randomFraction(random) * candidates.length)] };
}

/** A fresh, inclusive two-to-four-second search duration for each queue entry. */
export function matchmakingDelay(random = Math.random) {
  return 2000 + Math.floor(randomFraction(random) * 2001);
}
